- name: Install packages
  hosts: all
  become: true
  tasks:
    - name: Install wget on all hosts
      apt:
        name: wget
        state: present

    - name: Install unzip on demo hosts
      apt:
        name: unzip
        state: present

    - name: Install nginx on nginx host
      apt:
        name: nginx
        state: present
