- hosts: nginx
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Copy new HTML file to nginx
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

- hosts: docker
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
