- name: Dev environment setup
  group:
    name: Devs
    state: present

- name: Add a new user
  user:
    name: devsam
    state: present
    group: Devs

- name: Install zsh shell and curl
  package:
    name:
      - zsh
      - curl
    state: present

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Install and setup Jenkins
  package:
    name: jenkins
    state: present