---
- name: My Ansible Playbook
  hosts: all
  gather_facts: false

  vars:
    package_to_install: "{{ ansible_pkg_mgr | default('unzip') }}"
    repo_url: "{{ repo }}"
    file_path: "/path/to/file.txt"
    text_to_append: "{{ text }}"

  tasks:
    - name: Print name to console
      debug:
        msg: "Your Name"
      run_once: true

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "/path/to/destination"
      run_once: true

    - name: Install package
      package:
        name: "{{ package_to_install }}"
        state: present

    - name: Install nginx
      package:
        name: nginx
        state: present
      notify: restart nginx
      when: inventory_hostname == 'nginx'

    - name: Create new file and append text
      lineinfile:
        path: "{{ file_path }}"
        line: "{{ text_to_append }}"
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
